module.exports = {
    reporterEnabled: 'allure-cucumberjs',
    allureCucumberReporterOptions:{
        resultsDir: '.reports/allure-reports',
        useCucumberStepReporter: true,
        // disableWebdriverStepsReporting:true,
        // disbaleWebdriverScreenshotsReporting:false,
    },
    // cleanResultsDir: true,
    // cleanReportDir: true,
    // // reportTitle: 'My Project Test Report',
    // showSkipped: true,
    // showPassed: true,
    // showFailed: true,
    // showBroken: true,
    // showPending: true,
    // showUnknown: true,
    // showRetries: true,
    // showDuration: true,
    // showEnvironment: true,
    // showCategories: true,
    // showSeverity: true,
    // showOwner: true,
    // showHistory: true,
    // showTags: true,
    // showLinks: true,
    // showParameters: true,
    // showSteps: true,
    // showAttachments: true,
    // showIssues: true,
    // showTestCases: true,
    // showTestSuites: true,
    // showTestGroups: true,
    // showTestRuns: true,
    // showTestResults: true,
    // showTestSummary: true,
    // showTestDetails: true,
    // showTestLogs: true,
    // showTestScreenshots: true,
    // showTestVideos: true,
    // showTestArtifacts: true,
    // showTestMetadata: true,
    // showTestStatistics: true,
    // showTestCoverage: true,
    // showTestPerformance: true,
    // showTestAccessibility: true,
    // showTestUsability: true,
    // showTestSecurity: true,
    // showTestCompliance: true,
    // showTestReliability: true,
    // showTestMaintainability: true,
    // showTestPortability: true,
    // showTestCompatibility: true,
    // showTestInteroperability: true,
    // showTestScalability: true,
    // showTestAvailability: true,
    // showTestRecoverability: true,
    // showTestResilience: true,
    // showTestRobustness: true,
    // showTestAdaptability: true,
    // showTestFlexibility: true,
    // showTestExtensibility: true,
    // showTestModularity: true,
    // showTestReusability: true,
    // showTestConfigurability: true,
    // showTestCustomizability: true,
    // showTestIntegrability: true,
    // showTestDeployability: true,
    // showTestInstallability: true,
    // showTestUpgradability: true,
};